# Generated by Django 2.2.6 on 2019-10-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaEtiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('modelo', models.CharField(choices=[('BOLOS', 'Bolos'), ('LANCHES', 'Lanches')], default='BOLOS', max_length=20, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'folha de etiqueta',
                'verbose_name_plural': 'folhas de etiquetas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='FolhaEtiquetaItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('docura', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('folha_etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.FolhaEtiqueta')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('nome',),
            },
        ),
    ]
