# Generated by Django 2.2.6 on 2019-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhaetiquetaitens',
            name='docura',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2, verbose_name='Doçura'),
        ),
    ]
